server:
  servlet:
    context-path: /v1


app:
  name: syntechnica

  data-storage:
    internal-path: ${app.data-storage.path}/internal

  security:
    keystore:
      issuer: ${app.name}
      path: ${app.data-storage.internal-path}/keystore.p12
      jwt-signing-key:
        alias: jwtsigning
        password: ${app.security.keystore.password}

    auth:
      jwt:
        issuer: ${app.name}
        expiration-time: 2h
        claims:
          authorities: authorities
          version: version
